### PR TITLE
Tidy poly again.

### PR DESCRIPTION
**Pull request by memmett**

### CODE REVIEW

**Comment by memmett** [comment]
@torbjoernk Jenkins is barfing on some disk space calculation.  Can we disable that or do you find it useful?

**Comment by torbjoernk** [comment]
The diskspace calculation is not the problem. It failed on something else. I'm digging into that. I think, we just spammed Jenkins with too many build requests :wink:

**Comment by memmett** [comment]
Nice! Jenkins is buckling under the pressure of our super intense coding...

**Comment by torbjoernk** [comment]
If it keeps going like this, I'll apply for a few more build machines :smile:

**Comment by torbjoernk** [comment]
@pint-jenkins retest this please

**Pull request merged**
