### PR TITLE
Create implicit sweeper that supports LU decomposition of Q.

### PR DESCRIPTION
**Pull request by memmett**

### CODE REVIEW

**Comment by memmett** [comment]
Basic implicit sweeper appears to be working -- now for the LU part.

@danielru I changed the vdP example (and tests) to use the new implicit sweeper, but it doesn't (yet) support quadrature rules that include the left endpoint.  Are you OK with this?

**Comment by memmett** [comment]
@torbjoernk We don't want pivoting...

**Comment by memmett** [comment]
jenkins?  srsly?

**Comment by torbjoernk** [comment]
@pint-jenkins retest this please

**Pull request merged**
