### PR TITLE
Improve documentation all over the place

### PR DESCRIPTION
**Pull request by torbjoernk**
I'm improving the general documentation, slowly but steady. Still way to go.

### CODE REVIEW

**Comment by torbjoernk** [comment]
@pint-jenkins retest this please

**Comment by torbjoernk** [comment]
One may call this procrastination ... :flushed: :smile:

**Comment by torbjoernk** [comment]
@memmett Would you mind checking out the revamped docu at https://pint.fz-juelich.de/ci/job/PFASST_PULL_REQUESTS_DOCU/doxygen ?

I'd like to clean up this commit-mess before merging.

**Comment by torbjoernk** [comment]
so I've cleaned up that commit mess to be more descriptive and less confusing

**Comment by memmett** [comment]
Killer PR.  Only two comments:

1. At some point we agreed to capitalize the first word in the 'brief' doc string.  This PR seems to revert back to lower case.

2. On the doc server, I see "Changelog" repeated three times in the TOC.

**Comment by torbjoernk** [comment]
Fixed point one. Point two is most likely an artefact of having different versions of the documentation build in the same Jenkins job. When I build it locally in clean build folder it does not occur.

**Comment by torbjoernk** [comment]
@pint-jenkins retest this please

**Pull request merged**
