### PR TITLE
rework FFTW binding for AdvecDiffusion

### PR DESCRIPTION
**Pull request by torbjoernk**
Hopefully a little less hackish by prohibiting accidental copies of FFTW workspaces and storing the different workspaces in a single global manager.

`fftw_cleanup` is now called by the destructor of the manager, making the manual call to `fftw_cleanup` by the user obsolete.

### CODE REVIEW

**Comment by pancetta** [comment]
Can this deal with spatial parallelization / distributed data?

**Comment by torbjoernk** [comment]
@pancetta Not out of the box as a complete different set of FFTW3 routines have to be used.

We might want to parameterize the FFTWManager and have different FFTWWorkspace implementations for different FFTW3 modes.

Opinions, @memmett ?

**Comment by memmett** [comment]
Maybe we should use [FFTW++](https://github.com/dealias/fftwpp).  Then we'd get an easy interface to OpenMP and MPI based parallelism for the Fourier transforms for "free".

**Comment by pancetta** [comment]
Looks interesting! I don't see a reason why we need to distinguish between space serial and parallel fft whatsoever..

**Comment by torbjoernk** [comment]
I've adjusted the FFT Manager to be parameterized in the Workspace type, which is a theoretical concept (as documented in fftw_manager.hpp). That way we can work with different Workspace implementations.

The FFTWWorkspace concept should be seen as a wrapper around the actual calls some FFT libraries (FFTW, FFTW++, whatever). The Manager itself has no knowledge of FFT and the Workspace none of the Manager.

To use FFTW++, simple implement another FFTWWorkspace with the appropriate calls while complying with the concept.

**Comment by memmett** [comment]
I'm a little troubled that the workspaces are essentially global
variables.  I don't think the singleton pattern works well here -- what if
I have multidimensional problem and need to do several FFTs during an
f-eval?  With a single workspace there seems to be a high potential for one
to shoot oneself in the foot.

What does the singleton pattern buy us that a simple class (that the user
can instantiate multiple times without worrying about global state) doesn't?

**Comment by torbjoernk** [comment]
Valid point. You're right. I've fixed that.

**Pull request merged**
